# Generated by Django 4.2.2 on 2023-07-27 07:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='galary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_title', models.CharField(max_length=150)),
                ('title_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='title_pic')),
                ('title_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
