# Generated by Django 4.2.2 on 2023-08-11 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mountain_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_pic', models.ImageField(upload_to='story_pic')),
                ('story_title', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('about_story', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='galary',
            name='title_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='galary',
            name='title_pic',
            field=models.ImageField(upload_to='galary_pic'),
        ),
        migrations.CreateModel(
            name='yatra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('m', models.CharField(max_length=12)),
                ('pin', models.CharField(max_length=50)),
                ('adhar', models.CharField(max_length=12)),
                ('adres', models.CharField(max_length=612)),
                ('mobile', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='help_desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('issue_type', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('issue_explain', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
