# Generated by Django 4.2.2 on 2023-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_app', '0002_story_alter_galary_title_date_alter_galary_title_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yatra',
            old_name='adhar',
            new_name='texp',
        ),
        migrations.RemoveField(
            model_name='yatra',
            name='m',
        ),
        migrations.RemoveField(
            model_name='yatra',
            name='password',
        ),
        migrations.RemoveField(
            model_name='yatra',
            name='pin',
        ),
        migrations.AddField(
            model_name='yatra',
            name='afil',
            field=models.FileField(default=2, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yatra',
            name='edu',
            field=models.CharField(default=2, max_length=1210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yatra',
            name='spk',
            field=models.CharField(default=2, max_length=1288),
            preserve_default=False,
        ),
    ]
