# Generated by Django 4.2.2 on 2023-08-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_app', '0003_rename_adhar_yatra_texp_remove_yatra_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatra',
            name='name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
